<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ANasser-8470p" name="com.xirrus.xms.TS_Array_Services.TC_Services_Netflow" tests="11" failures="4" timestamp="25 Mar 2015 18:14:26 GMT" time="692.884" errors="0">
  <testcase name="testCase_verifyNetflowCollectorPortFieldValidation" time="108.961" classname="com.xirrus.xms.TS_Array_Services.TC_Services_Netflow">
    <failure type="java.lang.AssertionError" message="FAIL- Verification Failed!!!NetflowPortEmptyWarning-TC_Services_Netflow-testCase_verifyNetflowCollectorPortFieldValidation">
      <![CDATA[java.lang.AssertionError: FAIL- Verification Failed!!!NetflowPortEmptyWarning-TC_Services_Netflow-testCase_verifyNetflowCollectorPortFieldValidation
	at org.testng.Assert.fail(Assert.java:89)
	at com.xirrus.xms.locallib.LocalLib.verifyStringequals(LocalLib.java:128)
	at com.xirrus.xms.TS_Array_Services.TC_Services_Netflow.testCase_verifyNetflowCollectorPortFieldValidation(TC_Services_Netflow.java:731)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:965)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:961)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:890)
	at org.testng.TestNG.run(TestNG.java:824)
	at org.testng.TestNG.privateMain(TestNG.java:1128)
	at org.testng.TestNG.main(TestNG.java:1092)
]]>
    </failure>
  </testcase>
  <testcase name="testCase_verifyNetflowVersionV6" time="41.081" classname="com.xirrus.xms.TS_Array_Services.TC_Services_Netflow"/>
  <testcase name="testCase_verifyNetflowCollectorHostEdit" time="10.016" classname="com.xirrus.xms.TS_Array_Services.TC_Services_Netflow"/>
  <testcase name="testCase_verifyNetflowVersionV5" time="45.310" classname="com.xirrus.xms.TS_Array_Services.TC_Services_Netflow"/>
  <testcase name="testCase_verifyNetflowCollectorPortEdit" time="9.453" classname="com.xirrus.xms.TS_Array_Services.TC_Services_Netflow"/>
  <testcase name="testCase_verifyNetflowDefaultCollectorPort" time="28.882" classname="com.xirrus.xms.TS_Array_Services.TC_Services_Netflow"/>
  <testcase name="testCase_verifyNetflowVersionIPFIX" time="44.474" classname="com.xirrus.xms.TS_Array_Services.TC_Services_Netflow"/>
  <testcase name="testCase_verifyNetflowDefaultVersion" time="39.619" classname="com.xirrus.xms.TS_Array_Services.TC_Services_Netflow">
    <failure type="java.lang.AssertionError" message="FAIL- Verification Failed!!!NetflowState-TC_Services_Netflow-testCase_verifyNetflowDefaultVersion">
      <![CDATA[java.lang.AssertionError: FAIL- Verification Failed!!!NetflowState-TC_Services_Netflow-testCase_verifyNetflowDefaultVersion
	at org.testng.Assert.fail(Assert.java:89)
	at com.xirrus.xms.locallib.LocalLib.verifyStringequals(LocalLib.java:128)
	at com.xirrus.xms.TS_Array_Services.TC_Services_Netflow.testCase_verifyNetflowDefaultVersion(TC_Services_Netflow.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:965)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:961)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:890)
	at org.testng.TestNG.run(TestNG.java:824)
	at org.testng.TestNG.privateMain(TestNG.java:1128)
	at org.testng.TestNG.main(TestNG.java:1092)
]]>
    </failure>
  </testcase>
  <testcase name="testCase_verifyNetflowDefaultCollectorHost" time="83.491" classname="com.xirrus.xms.TS_Array_Services.TC_Services_Netflow"/>
  <testcase name="testCase_verifyNetflowDisable" time="159.292" classname="com.xirrus.xms.TS_Array_Services.TC_Services_Netflow">
    <failure type="java.lang.AssertionError" message="FAIL- Verification Failed!!!NetflowState-TC_Services_Netflow-testCase_verifyNetflowDisable">
      <![CDATA[java.lang.AssertionError: FAIL- Verification Failed!!!NetflowState-TC_Services_Netflow-testCase_verifyNetflowDisable
	at org.testng.Assert.fail(Assert.java:89)
	at com.xirrus.xms.locallib.LocalLib.verifyStringequals(LocalLib.java:128)
	at com.xirrus.xms.TS_Array_Services.TC_Services_Netflow.testCase_verifyNetflowDisable(TC_Services_Netflow.java:867)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:965)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:961)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:890)
	at org.testng.TestNG.run(TestNG.java:824)
	at org.testng.TestNG.privateMain(TestNG.java:1128)
	at org.testng.TestNG.main(TestNG.java:1092)
]]>
    </failure>
  </testcase>
  <testcase name="testCase_verifyNetflowCollectorHostFieldValidation" time="122.305" classname="com.xirrus.xms.TS_Array_Services.TC_Services_Netflow">
    <failure type="java.lang.AssertionError" message="FAIL- Verification Failed!!!NetflowHostInvalidNameWarning-TC_Services_Netflow-testCase_verifyNetflowCollectorHostFieldValidation">
      <![CDATA[java.lang.AssertionError: FAIL- Verification Failed!!!NetflowHostInvalidNameWarning-TC_Services_Netflow-testCase_verifyNetflowCollectorHostFieldValidation
	at org.testng.Assert.fail(Assert.java:89)
	at com.xirrus.xms.locallib.LocalLib.verifyStringequals(LocalLib.java:128)
	at com.xirrus.xms.TS_Array_Services.TC_Services_Netflow.testCase_verifyNetflowCollectorHostFieldValidation(TC_Services_Netflow.java:650)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:965)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:961)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:890)
	at org.testng.TestNG.run(TestNG.java:824)
	at org.testng.TestNG.privateMain(TestNG.java:1128)
	at org.testng.TestNG.main(TestNG.java:1092)
]]>
    </failure>
  </testcase>
</testsuite>
