<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ANasser-8470p" name="com.xirrus.xms.TS_Array_VLAN.TC_VLAN_AddVLANs" tests="6" failures="1" timestamp="25 Mar 2015 18:14:26 GMT" time="2289.810" errors="0">
  <testcase name="testCase_VerifyAddMultipleVLANs" time="128.913" classname="com.xirrus.xms.TS_Array_VLAN.TC_VLAN_AddVLANs"/>
  <testcase name="testCase_VerifyNewVLANDefaultValues" time="48.341" classname="com.xirrus.xms.TS_Array_VLAN.TC_VLAN_AddVLANs"/>
  <testcase name="testCase_VerifyThirdVLANValues" time="456.148" classname="com.xirrus.xms.TS_Array_VLAN.TC_VLAN_AddVLANs"/>
  <testcase name="testCase_VerifySecondVLANValues" time="455.415" classname="com.xirrus.xms.TS_Array_VLAN.TC_VLAN_AddVLANs"/>
  <testcase name="testCase_VerifyAddSingleVLAN" time="532.514" classname="com.xirrus.xms.TS_Array_VLAN.TC_VLAN_AddVLANs"/>
  <testcase name="testCase_VerifyMaxVLANSupportByArray" time="668.479" classname="com.xirrus.xms.TS_Array_VLAN.TC_VLAN_AddVLANs">
    <failure type="java.lang.AssertionError" message="FAIL- Verification Failed!!!MAXVLANLimitation-TC_VLAN_AddVLANs-testCase_VerifyMaxVLANSupportByArray">
      <![CDATA[java.lang.AssertionError: FAIL- Verification Failed!!!MAXVLANLimitation-TC_VLAN_AddVLANs-testCase_VerifyMaxVLANSupportByArray
	at org.testng.Assert.fail(Assert.java:89)
	at com.xirrus.xms.locallib.LocalLib.verifyStringequals(LocalLib.java:128)
	at com.xirrus.xms.TS_Array_VLAN.TC_VLAN_AddVLANs.testCase_VerifyMaxVLANSupportByArray(TC_VLAN_AddVLANs.java:932)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:965)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:961)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:890)
	at org.testng.TestNG.run(TestNG.java:824)
	at org.testng.TestNG.privateMain(TestNG.java:1128)
	at org.testng.TestNG.main(TestNG.java:1092)
]]>
    </failure>
  </testcase>
</testsuite>
